import { compile, zipDirectory, loadBlogSpace, renderWorkspaceIndex } from "@blogspace/compiler";
import { join } from "node:path";
import { rm, mkdir, writeFile, copyFile } from "node:fs/promises";

async function run() {
  const root = "c:\\Users\\vdhaw\\Documents\\blog\\fixtures";
  const exportRoot = join(root, "export");
  
  console.log("Cleaning export directory...");
  await rm(exportRoot, { recursive: true, force: true });
  await mkdir(exportRoot, { recursive: true });

  const spaceIds = ["bharat-bhraman", "book-reviews", "movie-reviews"];
  const seriesList = [];

  for (const spaceId of spaceIds) {
    const spaceDir = join(root, spaceId);
    const outDir = join(exportRoot, spaceId);
    console.log(`Compiling space: ${spaceId} → ${outDir}...`);
    
    const result = await compile({
      spaceDir,
      outDir,
      format: "dir"
    });
    console.log(`✓ Compiled ${spaceId}: chapters=${result.chaptersWritten}, images=${result.imagesProcessed}`);
    
    // Load series metadata for index rendering
    const space = await loadBlogSpace(spaceDir);
    seriesList.push(space.series);
  }

  console.log("Generating root index.html...");
  const indexHtml = renderWorkspaceIndex(seriesList);
  await writeFile(join(exportRoot, "index.html"), indexHtml, "utf8");

  // Copy global configurations from first space to root
  console.log("Copying global configurations to root...");
  const firstSpaceId = spaceIds[0];
  const firstSpaceOutDir = join(exportRoot, firstSpaceId);
  try {
    await copyFile(join(firstSpaceOutDir, "404.html"), join(exportRoot, "404.html"));
    await copyFile(join(firstSpaceOutDir, "favicon.svg"), join(exportRoot, "favicon.svg"));
    await copyFile(join(firstSpaceOutDir, "robots.txt"), join(exportRoot, "robots.txt"));
  } catch (err) {
    console.warn("Warning: Failed to copy some root config assets:", err.message);
  }

  // Create root _headers with recursive globbing
  console.log("Writing root _headers...");
  const rootHeaders = `# Generated by Blogspace. Cloudflare Pages caching + security headers.

/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin

# HTML always revalidates — URLs are stable, so freshness comes from 304s.
/
  Cache-Control: public, max-age=0, must-revalidate
/**/*.html
  Cache-Control: public, max-age=0, must-revalidate

# Immutable, width/format-keyed asset variants — cache for a year.
/**/assets/*
  Cache-Control: public, max-age=31536000, immutable

# Feeds, manifests and AI files — short shared cache, revalidate hourly.
/**/sitemap.xml
  Cache-Control: public, max-age=3600
/**/rss.xml
  Cache-Control: public, max-age=3600
/**/manifest.json
  Cache-Control: public, max-age=0, must-revalidate
/**/llms.txt
  Cache-Control: public, max-age=3600
/**/llms-full.txt
  Cache-Control: public, max-age=3600
`;
  await writeFile(join(exportRoot, "_headers"), rootHeaders, "utf8");

  // Create root llms.txt
  console.log("Writing root llms.txt...");
  const rootLlms = `# Blog Sphere

- [India we saw](/bharat-bhraman/llms.txt)
- [Book Reviews](/book-reviews/llms.txt)
- [Movie Reviews](/movie-reviews/llms.txt)
`;
  await writeFile(join(exportRoot, "llms.txt"), rootLlms, "utf8");

  console.log("Zipping export directory to export.zip...");
  const zipPath = join(root, "export.zip");
  await rm(zipPath, { force: true });
  await zipDirectory(exportRoot, zipPath);
  console.log(`✓ Export complete! Zip archive written to: ${zipPath}`);
}

run().catch(console.error);
