import { compile, zipDirectory, loadBlogSpace, renderWorkspaceIndex } from "@blogspace/compiler";
import { join } from "node:path";
import { rm, mkdir, writeFile, readFile, readdir, unlink } from "node:fs/promises";

const BASE_URL = "https://howiseeindia.com";

async function run() {
  const root = "c:\\Users\\vdhaw\\Documents\\blog\\fixtures";
  const exportRoot = join(root, "export");
  
  console.log("Cleaning export directory...");
  await rm(exportRoot, { recursive: true, force: true });
  await mkdir(exportRoot, { recursive: true });

  const spaceIds = ["bharat-bhraman", "book-reviews", "movie-reviews"];
  const seriesList = [];

  // ── 1. Compile each blog space ──
  for (const spaceId of spaceIds) {
    const spaceDir = join(root, spaceId);
    const outDir = join(exportRoot, spaceId);
    console.log(`Compiling space: ${spaceId} → ${outDir}...`);
    
    const result = await compile({
      spaceDir,
      outDir,
      format: "dir"
    });
    console.log(`  ✓ chapters=${result.chaptersWritten}, images=${result.imagesProcessed}`);
    
    const space = await loadBlogSpace(spaceDir);
    seriesList.push(space.series);
  }

  // ── 2. Generate root index.html (unified landing page) ──
  console.log("Generating root index.html...");
  const indexHtml = renderWorkspaceIndex(seriesList);
  await writeFile(join(exportRoot, "index.html"), indexHtml, "utf8");

  // ── 3. Remove per-blog files that must only exist at root ──
  //    Cloudflare Pages reads _headers, 404.html only from deploy root.
  //    Search engines read robots.txt only from domain root.
  //    There must be exactly ONE of each.
  // ── 3a. Copy favicon from first space BEFORE deleting per-blog files ──
  console.log("Copying root favicon.svg...");
  try {
    const faviconSrc = await readFile(join(exportRoot, spaceIds[0], "favicon.svg"), "utf8");
    await writeFile(join(exportRoot, "favicon.svg"), faviconSrc, "utf8");
  } catch (_) {
    console.warn("  Warning: could not read favicon from first space.");
  }

  // ── 3b. Remove per-blog files that must only exist at root ──
  //    Cloudflare Pages reads _headers, 404.html only from deploy root.
  //    Search engines read robots.txt only from domain root.
  //    There must be exactly ONE of each.
  const removeFromBlogs = ["_headers", "404.html", "robots.txt", "favicon.svg", "sitemap.xml", "rss.xml"];
  for (const spaceId of spaceIds) {
    for (const file of removeFromBlogs) {
      try {
        await unlink(join(exportRoot, spaceId, file));
      } catch (_) {}
    }
  }
  console.log("Removed per-blog root-only files.");

  // ── 4. Write root _headers (Cloudflare Pages) ──
  console.log("Writing root _headers...");
  await writeFile(join(exportRoot, "_headers"), `# Generated by Blogspace. Cloudflare Pages caching + security headers.

/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin

# HTML always revalidates — URLs are stable, freshness via 304.
/
  Cache-Control: public, max-age=0, must-revalidate
/**/*.html
  Cache-Control: public, max-age=0, must-revalidate

# Immutable asset variants — cache for a year.
/**/assets/**
  Cache-Control: public, max-age=31536000, immutable

# Viewer manifests and chat config in nested blog folders.
/**/manifest.json
  Cache-Control: public, max-age=0, must-revalidate
/**/chat-config.json
  Cache-Control: public, max-age=0, must-revalidate

# Feeds, manifests and AI files.
/sitemap.xml
  Cache-Control: public, max-age=3600
/rss.xml
  Cache-Control: public, max-age=3600
/**/llms.txt
/**/llms-full.txt
  Cache-Control: public, max-age=3600
`, "utf8");

  // ── 5. Write root 404.html ──
  console.log("Writing root 404.html...");
  await writeFile(join(exportRoot, "404.html"), `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Page not found</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; background: #fbfaf7; color: #1a1714; }
@media (prefers-color-scheme: dark) { body { background: #14120e; color: #f3eee4; } }
.box { text-align: center; max-width: 400px; padding: 2rem; }
h1 { font-size: 4rem; margin: 0 0 0.5rem; }
a { color: #a23a17; }
@media (prefers-color-scheme: dark) { a { color: #ec9874; } }
</style>
</head>
<body><div class="box"><h1>404</h1><p>This page doesn't exist.</p><p><a href="/">← Back to home</a></p></div></body>
</html>
`, "utf8");


  // ── 7. Write unified robots.txt ──
  console.log("Writing root robots.txt...");
  await writeFile(join(exportRoot, "robots.txt"), `User-agent: *
Allow: /

User-agent: GPTBot
Allow: /

User-agent: OAI-SearchBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: Claude-Web
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: CCBot
Allow: /

User-agent: Applebot-Extended
Allow: /

# LLM-friendly content manifests
# ${BASE_URL}/llms.txt
${spaceIds.map(id => `# ${BASE_URL}/${id}/llms.txt`).join("\n")}

Sitemap: ${BASE_URL}/sitemap.xml
`, "utf8");

  // ── 8. Write unified sitemap.xml ──
  //    Merge all per-blog sitemap <url> entries with corrected paths.
  console.log("Writing unified sitemap.xml...");
  let allUrls = "";
  // Add root landing page
  allUrls += `<url><loc>${BASE_URL}/</loc></url>\n`;
  for (const spaceId of spaceIds) {
    const perBlogSitemap = join(root, spaceId, ".blogspace", "build-cache.yaml");
    // Re-load the space to get chapter info
    const space = await loadBlogSpace(join(root, spaceId));
    const basePath = space.series.site?.basePath ?? `/${spaceId}/`;
    const base = `${BASE_URL}${basePath.replace(/\/$/, "")}`;
    
    // Blog landing page
    allUrls += `<url><loc>${base}/</loc>`;
    if (space.series.updatedAt) allUrls += `<lastmod>${space.series.updatedAt}</lastmod>`;
    allUrls += `</url>\n`;
    
    // Each chapter
    for (const ch of space.chapters) {
      const chUrl = `${base}/chapters/${ch.slug}.html`;
      allUrls += `<url><loc>${chUrl}</loc>`;
      const mod = ch.frontmatter.updatedAt || ch.frontmatter.publishedAt;
      if (mod) allUrls += `<lastmod>${mod}</lastmod>`;
      allUrls += `</url>\n`;
    }
    
    // LLMs files (so search engines index them)
    allUrls += `<url><loc>${base}/llms.txt</loc></url>\n`;
  }
  // Root llms.txt
  allUrls += `<url><loc>${BASE_URL}/llms.txt</loc></url>\n`;

  await writeFile(join(exportRoot, "sitemap.xml"), `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${allUrls}</urlset>
`, "utf8");

  // ── 9. Write unified rss.xml ──
  console.log("Writing unified rss.xml...");
  let allItems = "";
  for (const spaceId of spaceIds) {
    const space = await loadBlogSpace(join(root, spaceId));
    const basePath = space.series.site?.basePath ?? `/${spaceId}/`;
    const base = `${BASE_URL}${basePath.replace(/\/$/, "")}`;
    
    for (const ch of space.chapters) {
      const pubDate = ch.frontmatter.publishedAt
        ? new Date(ch.frontmatter.publishedAt).toUTCString()
        : "";
      allItems += `<item>
<title>${escapeXml(ch.frontmatter.title)} — ${escapeXml(space.series.title)}</title>
<link>${base}/chapters/${ch.slug}.html</link>
<guid isPermaLink="false">${base}/chapters/${ch.slug}</guid>
<description>${escapeXml(ch.frontmatter.summary)}</description>
${pubDate ? `<pubDate>${pubDate}</pubDate>` : ""}
</item>
`;
    }
  }
  await writeFile(join(exportRoot, "rss.xml"), `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title>Blog Sphere — howiseeindia.com</title>
<link>${BASE_URL}/</link>
<atom:link href="${BASE_URL}/rss.xml" rel="self" type="application/rss+xml"/>
<description>All blogs on howiseeindia.com</description>
<language>en</language>
${allItems}</channel>
</rss>
`, "utf8");

  // ── 10. Write root llms.txt (index pointing to per-blog files) ──
  console.log("Writing root llms.txt...");
  let llmsContent = `# Blog Sphere — howiseeindia.com

> A collection of travel journals, book reviews, and film essays.

## Blog Series

`;
  for (const spaceId of spaceIds) {
    const space = await loadBlogSpace(join(root, spaceId));
    const basePath = space.series.site?.basePath ?? `/${spaceId}/`;
    llmsContent += `- [${space.series.title}](${BASE_URL}${basePath}llms.txt): ${space.series.description}\n`;
    llmsContent += `  Full text: ${BASE_URL}${basePath}llms-full.txt\n`;
  }
  await writeFile(join(exportRoot, "llms.txt"), llmsContent, "utf8");

  // ── 11. Zip ──
  console.log("Zipping export directory...");
  const zipPath = join(root, "export.zip");
  await rm(zipPath, { force: true });
  await zipDirectory(exportRoot, zipPath);
  
  // ── Summary ──
  console.log("\n✓ Export complete!");
  console.log(`  Dir:  ${exportRoot}`);
  console.log(`  Zip:  ${zipPath}`);
  console.log(`\nRoot files:  index.html, _headers, 404.html, favicon.svg, robots.txt, sitemap.xml, rss.xml, llms.txt`);
  console.log(`Per-blog:    index.html, chapters/, assets/, manifest.json, chat-config.json, llms.txt, llms-full.txt, book.html`);
}

function escapeXml(str) {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

run().catch(console.error);
